Transform: AWS::Serverless-2016-10-31
Description: Template for Crawl application's resources
Parameters:
  NodeDependencyLayerLogicalID:
    Type: String
    Description: Logical ID of the layer containing common Node Dependencies
Resources:
  CrawlURLsSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 720 # Six times Lambda Function Timeout as per AWS recommendations
      ReceiveMessageWaitTimeSeconds: 20
  CrawlURLSQSAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CrawlURLsSendMessagePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - sqs:SendMessage
                Resource: !GetAtt CrawlURLsSQSQueue.Arn
                Effect: Allow
  URLsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: BaseUrl
          AttributeType: S
        - AttributeName: Pathname
          AttributeType: S
      KeySchema:
        - AttributeName: BaseUrl
          KeyType: HASH
        - AttributeName: Pathname
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  CrawlURLsFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: URLsTableWritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - dynamodb:PutItem
                Resource: !GetAtt URLsTable.Arn
                Effect: Allow
        - PolicyName: CrawlURLsSQSAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt CrawlURLsSQSQueue.Arn
                Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  CrawlURLsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: crawl-urls.handler
      Role: !GetAtt CrawlURLsFunctionRole.Arn
      Runtime: nodejs14.x
      CodeUri: ./functions/crawl-urls
      Description: Crawls a batch of URLs and stores accessible pathnames in DynamoDB
      Layers:
        - Ref: NodeDependencyLayerLogicalID
      Timeout: 120
      MemorySize: 256
      Events:
        CrawlURLsQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CrawlURLsSQSQueue.Arn
            BatchSize: 2
      Environment:
        Variables:
          TABLE_NAME: !Ref URLsTable
          MAX_REQUESTS_PER_CRAWL: 50
          MAX_CRAWL_DEPTH: 20
          ERROR_LOGGING_ENABLED: true
          APIFY_LOCAL_STORAGE_DIR: /tmp/apify_storage/
  PublishURLsTopic:
      Type: AWS::SNS::Topic
  PublishURLFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: URLsTableReadStreamPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !GetAtt URLsTable.StreamArn
                Effect: Allow
        - PolicyName: PublishURLsTopicPublishPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - sns:Publish
                Resource: !Ref PublishURLsTopic
                Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  PublishURLsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: publish-urls.handler
      Role: !GetAtt PublishURLFunctionRole.Arn
      Runtime: nodejs14.x
      CodeUri: ./functions/publish-urls
      Description: Publishes crawled URLs to an SNS Topic for subscribers
      Layers:
        - Ref: NodeDependencyLayerLogicalID
      Events:
        URLsTableStreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt URLsTable.StreamArn
            StartingPosition: LATEST
      Environment:
        Variables:
          TARGET_SNS_ARN: !Ref PublishURLsTopic
  URLsCRUDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: urls-crud.handler
      Runtime: nodejs14.x
      CodeUri: ./functions/urls-crud
      Description: CRUD function for the URLs Table
      Layers:
        - Ref: NodeDependencyLayerLogicalID
      Policies:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - Version: '2012-10-17'
        Statement:
        - Sid: URLsTableCRUDPolicy
          Effect: Allow
          Action:
          - dynamodb:Query
          Resource: !GetAtt URLsTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref URLsTable
          ERROR_LOGGING_ENABLED: true
  URLsCRUDAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: InvokeURLsCRUDFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt URLsCRUDFunction.Arn
                Effect: Allow
Outputs:
  QueueURL:
    Description: The URL of the Crawl URLs SQS Queue
    Value: !Ref CrawlURLsSQSQueue
  AccessRole:
    Description: IAM Role required to access the Crawl URLs SQS Queue
    Value: !GetAtt CrawlURLSQSAccessRole.Arn
  TopicARN:
    Description: The ARN for the Publish URLS SNS Topic
    Value: !Ref PublishURLsTopic
  URLCRUDFunctionARN:
    Description: The ARN for the CRUD function for the URLs Table
    Value: !GetAtt URLsCRUDFunction.Arn
  URLCRUDFunctionAccessRole:
    Description: The ARN of the IAM role required to allow api gateway to access the URLs CRUD function
    Value: !GetAtt URLsCRUDAccessRole.Arn
