openapi: "3.0.1"
info:
  title: 
    Fn::Sub: "buzzword-crawl-service-${EnvironmentNameSuffix}"
  description: "Crawl Service API Gateway"
  version: "1.0"
paths:
  /crawl:
    post:
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/invoke-crawl-state-machine"
  /urls/{baseUrl}:
    get:
      parameters: [
        {
          name: "baseUrl",
          in: "path",
          required: true,
          schema: {
            type: "string"
          }
        }
      ]
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/urls-crud-read-integration"
components:
  x-amazon-apigateway-integrations:
    invoke-crawl-state-machine:
      type: "aws_proxy"
      integrationSubtype: "StepFunctions-StartExecution"
      credentials:
        Fn::GetAtt:
        - "InvokeCrawlStateMachineRole"
        - "Arn"
      requestParameters:
        StateMachineArn:
          Ref: "CrawlStateMachine"
        Input: "$request.body.MessageBody"
      payloadFormatVersion: "1.0"
    urls-crud-read-integration:
      type: "aws_proxy"
      httpMethod: "POST"
      uri: 
        Fn::GetAtt:
        - "URLsCRUDFunction"
        - "Arn"
      credentials:
        Fn::GetAtt:
        - "URLsCRUDAccessRole"
        - "Arn"
      payloadFormatVersion: "1.0"
