env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  indent: ["error", 4],
  semi: ["error", "always"],
  max-len: ["error"],
  jest/no-disabled-tests: "warn",
  jest/no-focused-tests: "error",
  jest/no-identical-title: "error",
  jest/prefer-to-have-length: "warn",
  jest/valid-expect: "error"
}
plugins: ["jest"]
