Description: Overall template for the Buzzword Application AWS Stack
Resources:
  WibbleLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: wibble.handler
      Role:
        Fn::GetAtt:
          - 'LambdaExecutionRole'
          - 'Arn'
      Runtime: nodejs14.x
      Code: ../functions
      Description: Returns a wibble result
      Timeout: 10
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
