openapi: "3.0.1"
info:
  title: 
    Fn::Sub: "buzzword-http-gateway-${EnvironmentNameSuffix}"
  description: "Gateway to Buzzword Stack Resources"
  version: "1.0"
paths:
  /crawl:
    post:
      responses:
        default:
          description: "Default response for ANY /crawl request"
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/crawl-urls-sqs-send-message-integration"
components:
  x-amazon-apigateway-integrations:
    crawl-urls-sqs-send-message-integration:
      integrationSubtype: "SQS-SendMessage"
      credentials:
        Fn::GetAtt:
        - "CrawlApplication"
        - "Outputs.AccessRole"
      requestParameters:
        MessageBody: "$request.body.MessageBody"
        QueueUrl:
          Fn::GetAtt:
          - "CrawlApplication"
          - "Outputs.QueueURL"
      payloadFormatVersion: "1.0"
      type: "aws_proxy"
      connectionType: "INTERNET"
x-amazon-apigateway-importexport-version: "1.0"
