Transform: AWS::Serverless-2016-10-31
Description: Overall template for the Buzzword Application AWS Stack
Resources:
  NodeModuleDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes: 
        - nodejs14.x
      ContentUri: ../
      Description: Production node module dependency layer
    Metadata:
      BuildMethod: makefile
  CrawlURLsLambdaApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../applications/crawl/crawl-template.yml
      Parameters:
        NodeDependencyLayerLogicalID: !Ref NodeModuleDependencyLayer
  BuzzwordAPIAccessLogs:
    Type: AWS::Logs::LogGroup
  BuzzwordHTTPGateway:
    Type: AWS::Serverless::HttpApi
    DependsOn:
      - BuzzwordAPIAccessLogs
      - CrawlURLsLambdaApplication
    Properties:
      StageName: prod
      AccessLogSettings:
        DestinationArn: !GetAtt BuzzwordAPIAccessLogs.Arn
        Format: '{ "requestId":"$context.requestId", "errorMessage":"$context.error.message", "integrationErrorMessage":"$context.integrationErrorMessage" }'
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./buzzword-api-gateway-openapi-definition.yml
