Transform: AWS::Serverless-2016-10-31
Description: Overall template for the Buzzword Application AWS Stack
Resources:
  NodeModuleDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes: 
        - nodejs14.x
      ContentUri: ../
      Description: Production node module dependency layer
    Metadata:
      BuildMethod: makefile
  CrawlApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../applications/crawl/crawl-template.yml
      Parameters:
        NodeDependencyLayerLogicalID: !Ref NodeModuleDependencyLayer
  KeywordsApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../applications/keyphrase/keyphrase-template.yml
      Parameters:
        NodeDependencyLayerLogicalID: !Ref NodeModuleDependencyLayer
  KeywordPublishURLSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn:
      - CrawlApplication
    Properties:
      Queues:
        - !GetAtt KeywordsApplication.Outputs.QueueURL
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt KeywordsApplication.Outputs.QueueARN
  CrawledURLsSubscription:
    Type: AWS::SNS::Subscription
    DependsOn:
      - KeywordPublishURLSQSPolicy
    Properties:
      TopicArn: !GetAtt CrawlApplication.Outputs.TopicARN
      Endpoint: !GetAtt KeywordsApplication.Outputs.QueueARN
      Protocol: sqs
      RawMessageDelivery: true
  BuzzwordAPIAccessLogs:
    Type: AWS::Logs::LogGroup
  BuzzwordHTTPGateway:
    Type: AWS::Serverless::HttpApi
    DependsOn:
      - BuzzwordAPIAccessLogs
      - CrawledURLsSubscription
    Properties:
      StageName: prod
      AccessLogSettings:
        DestinationArn: !GetAtt BuzzwordAPIAccessLogs.Arn
        Format: '{ "requestId":"$context.requestId", "errorMessage":"$context.error.message", "integrationErrorMessage":"$context.integrationErrorMessage" }'
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./buzzword-api-gateway-openapi-definition.yml
