Transform: AWS::Serverless-2016-10-31
Description: Template for Socket application's resources
Parameters:
  ApiGatewayName:
    Type: String
    Description: The name of the Web Socket API Gateway
  NodeDependencyLayerLogicalID:
    Type: String
    Description: 'Logical ID of the layer containing common Node Dependencies'
  SearchKey:
    Type: String
    Description: The hash key to search for relevant table updates
  SearchKeyPattern:
    Type: String
    Description: RegEx pattern to validate the search key value
  TableName:
    Type: String
    Description: The name of the table to get updates from
  TableArn:
    Type: String
    Description: The ARN of the table to get updates from
  TableStreamArn:
    Type: String
    Description: The Stream ARN of the table to get updates from
Resources:
  ActiveConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ConnectionId
          AttributeType: S
        - AttributeName: SearchKey
          AttributeType: S
      KeySchema:
        - AttributeName: ConnectionId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      GlobalSecondaryIndexes:
        - IndexName: SearchKeyIndex
          KeySchema:
            - AttributeName: SearchKey
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  ConnectionManagerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ManageConnectionTablePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource: !GetAtt ActiveConnectionsTable.Arn
                Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  ConnectionManager:
    Type: AWS::Serverless::Function
    Properties:
      Handler: connection-manager.handler
      Role: !GetAtt ConnectionManagerRole.Arn
      Runtime: nodejs14.x
      CodeUri: ./functions/connection-manager
      Description: Manages active web socket connections
      Layers:
        - Ref: NodeDependencyLayerLogicalID
      Environment:
        Variables:
          TABLE_NAME: !Ref ActiveConnectionsTable
          ERROR_LOGGING_ENABLED: true
          SEARCH_KEY: !Ref SearchKey
          SEARCH_KEY_PATTERN: !Ref SearchKeyPattern
  SocketGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref ApiGatewayName
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  ConnectionManagerAccessPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ConnectionManager
      Principal: apigateway.amazonaws.com
  ConnectionIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SocketGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !GetAtt ConnectionManager.Arn
          - /invocations
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SocketGateway
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectionIntegration
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SocketGateway
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectionIntegration
  ConnectionDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
    Properties:
      ApiId: !Ref SocketGateway
  SocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: prod
      DeploymentId: !Ref ConnectionDeployment
      ApiId: !Ref SocketGateway
  WebSocketWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Provides ability to manage web socket api connections
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - execute-api:ManageConnections
            Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SocketGateway}/*"
            Effect: Allow
  NewConnectionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ActiveConnectionsTableReadStreamPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !GetAtt ActiveConnectionsTable.StreamArn
                Effect: Allow
        - PolicyName: SearchTableQueryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - dynamodb:Query
                Resource: !Ref TableArn
                Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole   
        - !Ref WebSocketWritePolicy
  NewConnection:
    Type: AWS::Serverless::Function
    Properties:
      Handler: new-connection.handler
      Role: !GetAtt NewConnectionRole.Arn
      Runtime: nodejs14.x
      CodeUri: ./functions/new-connection
      Description: Provides new connections with current database state
      Layers:
        - Ref: NodeDependencyLayerLogicalID
      Events:
        ActiveConnectionsStreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt ActiveConnectionsTable.StreamArn
            BatchSize: 10
            StartingPosition: TRIM_HORIZON
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          SEARCH_KEY: !Ref SearchKey
          SEARCH_KEY_PATTERN: !Ref SearchKeyPattern
  UpdateConnectionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ActiveConnectionsTableQueryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - dynamodb:Query
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt ActiveConnectionsTable.Arn
                  - !Sub "${ActiveConnectionsTable.Arn}/index/SearchKeyIndex"
                Effect: Allow
        - PolicyName: SearchTableReadStreamPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !Ref TableStreamArn
                Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole   
        - !Ref WebSocketWritePolicy
  UpdateConnections:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update-connections.handler
      Role: !GetAtt UpdateConnectionsRole.Arn
      Runtime: nodejs14.x
      CodeUri: ./functions/update-connections
      Description: Provides existing connections with relevant database updates
      Layers:
        - Ref: NodeDependencyLayerLogicalID
      Events:
        UpdatesStreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !Ref TableStreamArn
            BatchSize: 10
            StartingPosition: TRIM_HORIZON
      Environment:
        Variables:
          TABLE_NAME: !Ref ActiveConnectionsTable
          INDEX_NAME: SearchKeyIndex
          SEARCH_KEY: !Ref SearchKey
