openapi: "3.0.1"
info:
  title: 
    Fn::Sub: "buzzword-http-gateway-${EnvironmentNameSuffix}"
  description: "Gateway to Buzzword Stack Resources"
  version: "1.0"
paths:
  /keyphrases/{baseUrl}:
    get:
      parameters: [
        {
          name: "baseUrl",
          in: "path",
          required: true,
          schema: {
            type: "string"
          }
        }
      ]
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/keyphrases-crud-read-integration"
components:
  x-amazon-apigateway-integrations:
    keyphrases-crud-read-integration:
      type: "aws_proxy"
      httpMethod: "POST"
      uri:
        Fn::GetAtt:
        - "KeywordsApplication"
        - "Outputs.KeyphrasesCRUDFunctionARN"
      credentials:
        Fn::GetAtt:
        - "KeywordsApplication"
        - "Outputs.KeyphrasesCRUDFunctionAccessRole"
      payloadFormatVersion: "1.0"
x-amazon-apigateway-importexport-version: "1.0"
