Transform: AWS::Serverless-2016-10-31
Description: Overall template for the Buzzword Application AWS Stack
Parameters:
  EnvironmentNameSuffix:
    Type: String
    Default: dev
    Description: Environment name to be suffixed to buzzword resources
  CrawlTopicARN:
    Type: String
    Description: The ARN of the Crawl service's SNS Topic
Resources:
  NodeModuleDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub NodeModuleDependencyLayer-${EnvironmentNameSuffix}
      CompatibleRuntimes: 
        - nodejs14.x
      ContentUri: ../
      Description: Production node module dependency layer
    Metadata:
      BuildMethod: makefile
  KeywordsApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../dist/applications/keyphrase/keyphrase-template.yml
      Parameters:
        NodeDependencyLayerLogicalID: !Ref NodeModuleDependencyLayer
  KeywordPublishURLSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !GetAtt KeywordsApplication.Outputs.QueueURL
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt KeywordsApplication.Outputs.QueueARN
  CrawledURLsSubscription:
    Type: AWS::SNS::Subscription
    DependsOn:
      - KeywordPublishURLSQSPolicy
    Properties:
      TopicArn: !Ref CrawlTopicARN
      Endpoint: !GetAtt KeywordsApplication.Outputs.QueueARN
      Protocol: sqs
      RawMessageDelivery: true
  BuzzwordHTTPGateway:
    Type: AWS::Serverless::HttpApi
    DependsOn:
      - CrawledURLsSubscription
    Properties:
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./buzzword-rest-gateway-openapi-definition.yml
  KeywordsSocketApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../dist/applications/socket/socket-template.yml
      Parameters:
        ApiGatewayName: !Sub buzzword-keywords-socket-gateway-${EnvironmentNameSuffix}
        NodeDependencyLayerLogicalID: !Ref NodeModuleDependencyLayer
        SearchKey: BaseUrl
        SearchKeyPattern: '^(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$'
        TableName: !GetAtt KeywordsApplication.Outputs.TableName
        TableArn: !GetAtt KeywordsApplication.Outputs.TableArn
        TableStreamArn: !GetAtt KeywordsApplication.Outputs.TableStreamArn
