Transform: AWS::Serverless-2016-10-31
Description: Overall template for the Buzzword Application AWS Stack
Parameters:
  EnvironmentNameSuffix:
    Type: String
    Default: dev
    Description: Environment name to be suffixed to buzzword resources
  SocketTableName:
    Type: String
    Description: The name of the table for the web socket application to listen to
  SocketTableARN:
    Type: String
    Description: The ARN of the table for the web socket application to listen to
  SocketTableSreamARN:
    Type: String
    Description: The Stream ARN of the table for the web socket application to listen to
Resources:
  NodeModuleDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub NodeModuleDependencyLayer-${EnvironmentNameSuffix}
      CompatibleRuntimes: 
        - nodejs14.x
      ContentUri: ../
      Description: Production node module dependency layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  KeywordsSocketApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../dist/applications/socket/socket-template.yml
      Parameters:
        ApiGatewayName: !Sub buzzword-keywords-socket-gateway-${EnvironmentNameSuffix}
        NodeDependencyLayerLogicalID: !Ref NodeModuleDependencyLayer
        SearchKey: BaseUrl
        SearchKeyPattern: '^(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$'
        TableName: !Ref SocketTableName
        TableArn: !Ref SocketTableARN
        TableStreamArn: !Ref SocketTableSreamARN
