version = 0.1
[default.deploy.parameters]
stack_name = "buzzword-stack-dev"
s3_bucket = "buzzword-bucket"
s3_prefix = "buzzword-stack-dev"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "EnvironmentNameSuffix=dev"

[production.deploy.parameters]
stack_name = "buzzword-stack-prod"
s3_bucket = "buzzword-bucket"
s3_prefix = "buzzword-stack-prod"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "EnvironmentNameSuffix=prod"
