Transform: AWS::Serverless-2016-10-31
Description: Keyphrase Service
Parameters:
  EnvironmentNameSuffix:
    Type: String
    Description: Environment name suffixed to service resources
    Default: dev
  CrawlTopicARN:
    Type: String
    Description: The ARN of the Crawl service's SNS Topic
Resources:
  KeyphraseNodeDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub KeyphraseNodeDependencyLayer-${EnvironmentNameSuffix}
      Description: Common keyphrase service node module layer
      CompatibleRuntimes:
        - nodejs14.x
      ContentUri: ./functions
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  KeyphrasesURLsSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 180 # Six times Lambda Function Timeout as per AWS recommendations
      ReceiveMessageWaitTimeSeconds: 20
  CrawlTopicQueuePublishPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref KeyphrasesURLsSQSQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt KeyphrasesURLsSQSQueue.Arn
            Condition:
              ArnEquals:
                aws:sourceArn: !Ref CrawlTopicARN
  CrawlTopicSubscription:
    Type: AWS::SNS::Subscription
    DependsOn:
      - CrawlTopicQueuePublishPolicy
    Properties:
      TopicArn: !Ref CrawlTopicARN
      Endpoint: !GetAtt KeyphrasesURLsSQSQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true
  KeyphrasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: BaseUrl
          AttributeType: S
        - AttributeName: KeyPhrase
          AttributeType: S
      KeySchema:
        - AttributeName: BaseUrl
          KeyType: HASH
        - AttributeName: KeyPhrase
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  FindKeyphrasesFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub KeyphraseURLsSQSAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt KeyphrasesURLsSQSQueue.Arn
                Effect: Allow
        - PolicyName: !Sub KeyphrasesTableWritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - dynamodb:PutItem
                  - dynamodb:Query
                Resource: !GetAtt KeyphrasesTable.Arn
                Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  FindPhrasesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: find-keyphrases.handler
      Role: !GetAtt FindKeyphrasesFunctionRole.Arn
      Runtime: nodejs14.x
      CodeUri: ./functions/find-keyphrases
      Description: Finds the top 5 key words and key phrases and stores them in DynamoDB
      Layers:
        - Ref: KeyphraseNodeDependencyLayer
      Timeout: 30
      MemorySize: 256
      Events:
        KeyphrasesURLsQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt KeyphrasesURLsSQSQueue.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref KeyphrasesTable
  KeyphrasesCRUDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: keyphrases-crud.handler
      Runtime: nodejs14.x
      CodeUri: ./functions/keyphrases-crud
      Description: CRUD function for the Keyphrases Table
      Layers:
        - Ref: KeyphraseNodeDependencyLayer
      Policies:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - Version: '2012-10-17'
        Statement:
        - Sid: KeyphrasesTableCRUDPolicy
          Effect: Allow
          Action:
          - dynamodb:Query
          Resource: !GetAtt KeyphrasesTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref KeyphrasesTable
          ERROR_LOGGING_ENABLED: true
  KeyphrasesCRUDAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Sub InvokeKeyphrasesCRUDFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt KeyphrasesCRUDFunction.Arn
                Effect: Allow
  KeyphraseHTTPGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./keyphrase-openapi.yml
Outputs:
  QueueARN:
    Description: The ARN of the Keyphrases URLs SQS Queue
    Value: !GetAtt KeyphrasesURLsSQSQueue.Arn
  QueueURL:
    Description: The URL of the Keyphrases URLs SQS Queue
    Value: !Ref KeyphrasesURLsSQSQueue
  TableName:
    Description: The name of the Keyphrases Table
    Value: !Ref KeyphrasesTable
  TableArn:
    Description: The ARN of the Keyphrases Table
    Value: !GetAtt KeyphrasesTable.Arn
  TableStreamArn:
    Description: The ARN of the Keyphrases Table's Stream
    Value: !GetAtt KeyphrasesTable.StreamArn
  KeyphrasesCRUDFunctionARN:
    Description: The ARN for the CRUD function for the Keyphrases Table
    Value: !GetAtt KeyphrasesCRUDFunction.Arn
  KeyphrasesCRUDFunctionAccessRole:
    Description: The ARN of the IAM role required to allow api gateway to access the Keyphrases CRUD function
    Value: !GetAtt KeyphrasesCRUDAccessRole.Arn
