openapi: "3.0.1"
info:
  title: 
    Fn::Sub: "buzzword-keyphrase-service-${EnvironmentNameSuffix}"
  description: "Keyphrase Service API Gateway"
  version: "1.0"
paths:
  /keyphrases/{baseUrl}:
    get:
      parameters: [
        {
          name: "baseUrl",
          in: "path",
          required: true,
          schema: {
            type: "string"
          }
        }
      ]
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/keyphrases-crud-read-integration"
components:
  x-amazon-apigateway-integrations:
    keyphrases-crud-read-integration:
      type: "aws_proxy"
      httpMethod: "POST"
      uri:
        Fn::GetAtt:
        - "KeyphrasesCRUD"
        - "Arn"
      credentials:
        Fn::GetAtt:
        - "KeyphrasesCRUDAccessRole"
        - "Arn"
      payloadFormatVersion: "1.0"
