version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "buzzword-stack"
s3_bucket = "buzzword-bucket"
s3_prefix = "buzzword-stack"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
