name: Validate and Deploy - Keyphrase Service

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-deploy:
        name: Keyphrase
        uses: ./.github/workflows/service.yml
        with:
            service_cache_key: keyphrase-service
            path: ./services/keyphrase
            deploy_script_path: ./scripts/deploy-keyphrase-service.sh
            service_name: Keyphrase Service
        secrets:
            deploy_role: ${{ secrets.AWS_DEPLOY_ROLE }}
