name: Validate and Deploy

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-deploy-object-validator-package:
        name: Object Validator Package
        uses: ./.github/workflows/package.yml
        with:
            path: ./packages/object-validator
            node_cache_key: object-validator
    build-deploy-crawl-client-package:
        name: Crawl Client Package
        uses: ./.github/workflows/package.yml
        with:
            path: ./packages/crawl-client
            node_cache_key: crawl-client
    build-deploy-crawl-service:
        name: Crawl Service
        uses: ./.github/workflows/service.yml
        with:
            service_cache_key: crawl-service
            path: ./services/crawl
            deploy_script_path: ./scripts/deploy-crawl-service.sh
            service_name: Crawl Service
        secrets:
            deploy_role: ${{ secrets.AWS_DEPLOY_ROLE }}
    build-deploy-keyphrase-service:
        name: Keyphrase Service
        uses: ./.github/workflows/service.yml
        with:
            service_cache_key: keyphrase-service
            path: ./services/keyphrase
            deploy_script_path: ./scripts/deploy-keyphrase-service.sh
            service_name: Keyphrase Service
        secrets:
            deploy_role: ${{ secrets.AWS_DEPLOY_ROLE }}
    build-deploy-ui:
        name: UI
        uses: ./.github/workflows/ui.yml
        with:
            path: ./ui
        secrets:
            DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: scottbrenner/cfn-lint-action@v2.2.8
            - name: Validate Templates
              run: |
                  xargs -r0a <(find ./templates/ -name *-template.yml -print0) -I {} sh -c 'cfn-lint {} -i W3002 -i W3045'
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Run formatters
              run: |
                  npx prettier@^2.5.1 --check . '!services/**' '!packages/**' '!ui/**'
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - name: Cache Node Dependencies
              uses: actions/cache@v3
              env:
                  cache-name: ci-lint
              with:
                  path: |
                      ./node_modules
                      ./ui/node_modules
                  key: ${{ runner.os }}-node-v1-${{ env.cache-name }}-${{ hashFiles('./package-lock.json', './ui/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-v1-${{ env.cache-name }}-
            - name: Install Dependencies
              run: |
                  npx lerna@^5.5.2 bootstrap --scope "{how-many-buzzwords,how-many-buzzwords-ui}"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run linters
              run: |
                  ./node_modules/.bin/eslint '.' --max-warnings 0 --ext .js,.jsx,.ts,.tsx --ignore-pattern 'services/**' --ignore-pattern 'packages/**' --ignore-pattern 'ui/**'
                  ./node_modules/.bin/npmPkgJsonLint ./package.json
