name: Test (All), Validate (All), and Deploy (Master Only)
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: |
          find -name package.json -execdir npm ci \;
      - name: Run Unit Tests
        run: |
          npm --prefix ./aws/ run test
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VALIDATE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VALIDATE_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Validate Templates
        run: |
          sam validate --template ./aws/templates/buzzword-bucket-template.yml
          sam validate --template ./aws/templates/buzzword-template.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [test, validate]
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Deploy stack
        run: |
          cd ./aws/scripts
          ./deploy.sh -f -e production
