name: Validate - Development Files and Dependencies

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: scottbrenner/cfn-lint-action@v2.2.8
            - name: Validate Templates
              run: |
                  xargs -n1 -r0a <(find ./templates/ -name *-template.yml -print0) cfn-lint
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Run formatters
              run: |
                  npx prettier --check . '!services/**' '!packages/**' '!ui/**'
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - name: Cache Node Dependencies
              uses: actions/cache@v3
              env:
                  cache-name: ci-lint
              with:
                  path: |
                      ./node_modules
                      ./ui/node_modules
                  key: ${{ runner.os }}-node-v1-${{ env.cache-name }}-${{ hashFiles('./package-lock.json', './ui/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-v1-${{ env.cache-name }}-
            - name: Install Dependencies
              run: |
                  npx lerna bootstrap --scope "{how-many-buzzwords,how-many-buzzwords-ui}"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run linters
              run: |
                  ./node_modules/.bin/eslint '.' --max-warnings 0 --ext .js,.jsx,.ts,.tsx --ignore-pattern 'services/**' --ignore-pattern 'packages/**' --ignore-pattern 'ui/**'
                  ./node_modules/.bin/npmPkgJsonLint ./package.json
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - name: Audit Dependencies
              run: |
                  npm audit --audit-level=critical
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
