name: Validate and Deploy
on: [push]

jobs:
    build-deploy-object-validator-package:
        name: Object Validator Package
        uses: ./.github/workflows/package.yml
        with:
            path: ./packages/object-validator
    build-deploy-crawl-service:
        name: Crawl Service
        uses: ./.github/workflows/service.yml
        with:
            service_cache_key: crawl-service
            path: ./services/crawl
            deploy_script_path: ./scripts/deploy-crawl-service.sh
        secrets:
            deploy_role: ${{ secrets.AWS_DEPLOY_ROLE }}
    build-deploy-keyphrase-service:
        name: Keyphrase Service
        uses: ./.github/workflows/service.yml
        with:
            service_cache_key: keyphrase-service
            path: ./services/keyphrase
            deploy_script_path: ./scripts/deploy-keyphrase-service.sh
        secrets:
            deploy_role: ${{ secrets.AWS_DEPLOY_ROLE }}
    build-deploy-ui:
        name: UI
        uses: ./.github/workflows/ui.yml
        with:
            path: ./ui
        secrets:
            deploy_role: ${{ secrets.AWS_DEPLOY_ROLE }}
            region: ${{ secrets.CRAWL_SERVICE_ENDPOINT }}
            crawl_service_graphql_endpoint: ${{ secrets.CRAWL_SERVICE_ENDPOINT }}
            crawl_identity_pool_id: ${{ secrets.CRAWL_IDENTITY_POOL_ID }}
            keyphrase_service_ws_endpoint: ${{ secrets.KEYPHRASE_WS_SERVICE_ENDPOINT }}
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: scottbrenner/cfn-lint-action@v2
            - name: Validate Templates
              run: |
                  xargs -n1 -r0a <(find ./templates/ -name *-template.yml -print0) cfn-lint
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Run formatters
              run: |
                  npx prettier --check . '!services/**' '!packages/**' '!ui/**'
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - name: Install Dependencies
              run: |
                  npm ci
                  npm --prefix ./ui/ ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run linters
              run: |
                  ./node_modules/.bin/eslint '.' --max-warnings 0 --ext .js,.jsx,.ts,.tsx --ignore-pattern 'services/**' --ignore-pattern 'packages/**' --ignore-pattern 'ui/**'
                  ./node_modules/.bin/npmPkgJsonLint ./package.json
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - name: Audit Dependencies
              run: |
                  npm audit --audit-level=critical
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
