name: Validate and Deploy
on: [push]

jobs:
    build-deploy-object-validator-package:
        name: Object Validator Package
        uses: ./.github/workflows/package.yml
        with:
            path: ./packages/object-validator
    build-deploy-crawl-service:
        name: Crawl Service
        uses: ./.github/workflows/service.yml
        with:
            service_cache_key: crawl-service
            path: ./services/crawl
            deploy_script_path: ./scripts/deploy-crawl-service.sh
        secrets:
            deploy_role: ${{ secrets.AWS_DEPLOY_ROLE }}
    build-deploy-keyphrase-service:
        name: Keyphrase Service
        uses: ./.github/workflows/service.yml
        with:
            service_cache_key: keyphrase-service
            path: ./services/keyphrase
            deploy_script_path: ./scripts/deploy-keyphrase-service.sh
        secrets:
            deploy_role: ${{ secrets.AWS_DEPLOY_ROLE }}
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: scottbrenner/cfn-lint-action@v2
            - name: Validate Templates
              run: |
                  xargs -n1 -r0a <(find -name *-template.yml -print0) cfn-lint
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Run formatters
              run: |
                  npm run format:check
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - name: Install Dependencies
              run: |
                  npm run ci:sequential
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run linters
              run: |
                  npm run lint
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - name: Audit Dependencies
              run: |
                  npm run audit:parallel
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
