on:
    workflow_call:
        inputs:
            path:
                required: true
                type: string

jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Install Dependencies
              run: |
                  npm ci
                  npm --prefix ${{ inputs.path }} ci
            - name: Compile Package
              run: |
                  ./node_modules/.bin/tsc --project ${{ inputs.path }}
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Install Dependencies
              run: |
                  npm ci
                  npm --prefix ${{ inputs.path }} ci
            - name: Run Unit Tests
              run: |
                  ./node_modules/.bin/jest --testPathPattern=${{ inputs.path }}
    publish:
        runs-on: ubuntu-latest
        needs: [compile, unit-test]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  scope: "@ashley-evans"
            - name: Compile Package
              run: |
                  ./scripts/compile-package.sh -c -p ${{ inputs.path }}
            - name: Publish Package
              run: |
                  npm publish ./dist
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
