on:
    workflow_call:
        inputs:
            path:
                required: true
                type: string

jobs:
    changed:
        runs-on: ubuntu-latest
        outputs:
            package: ${{ steps.filter.outputs.package }}
        steps:
            - uses: actions/checkout@v2
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  base: master
                  filter: |
                      package:
                          - ${{ inputs.path }}/**
    compile:
        runs-on: ubuntu-latest
        needs: changed
        if: ${{ needs.changed.outputs.package == 'true' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Compile Package
              run: |
                  ./scripts/compile-package.sh -c -p ${{ inputs.path }}
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Audit Dependencies
              run: |
                  npm audit --prefix ${{ inputs.path }}
    format:
        runs-on: ubuntu-latest
        needs: changed
        if: ${{ needs.changed.outputs.package == 'true' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Run formatters
              run: |
                  npx prettier --check ${{ inputs.path }}
    lint:
        runs-on: ubuntu-latest
        needs: changed
        if: ${{ needs.changed.outputs.package == 'true' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Install Dependencies
              run: |
                  npm ci
                  npm --prefix ${{ inputs.path }} ci
            - name: Run linters
              run: |
                  ./node_modules/.bin/eslint ${{ inputs.path }} --max-warnings 0 --ext .js,.jsx,.ts,.tsx
                  ./node_modules/.bin/npmPkgJsonLint ${{ inputs.path }}
    unit-test:
        runs-on: ubuntu-latest
        needs: changed
        if: ${{ needs.changed.outputs.package == 'true' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Install Dependencies
              run: |
                  npm ci
                  npm --prefix ${{ inputs.path }} ci
            - name: Run Unit Tests
              run: |
                  ./node_modules/.bin/jest --testPathPattern=${{ inputs.path }}
    publish:
        runs-on: ubuntu-latest
        needs: [compile, audit, format, lint, unit-test]
        if: ${{ github.ref == 'refs/heads/master' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - name: Compile Package
              run: |
                  ./scripts/compile-package.sh -c -p ${{ inputs.path }}
            - name: Publish Package
              run: |
                  ./scripts/publish-package.sh -p ./dist
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
