on:
    workflow_call:
        inputs:
            dryrun:
                required: true
                type: boolean
        secrets:
            DEPLOY_ROLE:
                required: true

jobs:
    bundle:
        runs-on: ubuntu-latest
        if: ${{ !inputs.dryrun }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - name: Cache Node Dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ./node_modules
                      ./ui/node_modules
                  key: ${{ runner.os }}-node-v1-ui-${{ hashFiles('./package-lock.json', './ui/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-v1-ui-
            - name: Build UI
              run: |
                  npm --prefix ${{ inputs.path }} run build
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    deploy-dryrun:
        runs-on: ubuntu-latest
        if: ${{ inputs.dryrun }}
        permissions:
            id-token: write
            contents: read
            packages: read
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.8"
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  scope: "@ashley-evans"
                  registry-url: "https://npm.pkg.github.com"
            - uses: aws-actions/setup-sam@v2
            - name: Fix SAM Cryptography
              run: $(dirname $(readlink $(which sam)))/pip install --force-reinstall "cryptography==38.0.4"
            - uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-region: eu-west-2
                  role-to-assume: ${{ secrets.DEPLOY_ROLE }}
            - name: Cache Node Dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ./node_modules
                      ./ui/node_modules
                  key: ${{ runner.os }}-node-v1-ui-${{ hashFiles('./package-lock.json', './ui/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-v1-ui-
            - name: Dry Run Deployment
              id: dry-run
              run: |
                  ./scripts/helpers/write-changeset-to-file.sh -c "./scripts/deploy-ui.sh -e production -d -c" \
                    -f $GITHUB_OUTPUT \
                    -v CHANGESET_OUTPUT \
                    -d EOF
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        outputs:
            CHANGESET_OUTPUT: ${{ steps.dry-run.outputs.CHANGESET_OUTPUT }}
    add-changeset-comment:
        runs-on: ubuntu-latest
        needs: deploy-dryrun
        if: ${{ github.event_name == 'pull_request' && needs.deploy-dryrun.outputs.CHANGESET_OUTPUT != '' }}
        steps:
            - uses: actions/checkout@v3
            - name: Find Comment
              uses: peter-evans/find-comment@v2
              id: find-comment
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: "github-actions[bot]"
                  body-includes: "How Many Buzzwords UI"
            - name: Create Multiline changeset YAML variable for template
              run: |
                  ./scripts/helpers/multiline-string-to-yml.sh -k changeset \
                    -v "${{ needs.deploy-dryrun.outputs.CHANGESET_OUTPUT }}" \
                    -o ./template_vars.yml
            - name: Create comment template
              uses: chuhlomin/render-template@v1.6
              id: template
              with:
                  template: .github/comment_template/changeset-template.md
                  vars: |
                      service_name: "How Many Buzzwords UI"
                  vars_path: ./template_vars.yml
            - name: Create or update comment
              uses: peter-evans/create-or-update-comment@v2
              with:
                  comment-id: ${{ steps.find-comment.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body: ${{ steps.template.outputs.result }}
                  edit-mode: replace
