on:
    workflow_call:
        inputs:
            path:
                required: true
                type: string

jobs:
    changed:
        runs-on: ubuntu-latest
        outputs:
            ui: ${{ steps.filter.outputs.ui }}
        steps:
            - uses: actions/checkout@v2
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  base: master
                  filters: |
                      ui:
                        - ${{ inputs.path }}/**
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Audit Dependencies
              run: |
                  npm audit --prefix ${{ inputs.path }}
    build:
        runs-on: ubuntu-latest
        needs: changed
        if: ${{ needs.changed.outputs.ui == 'true' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install dependencies
              run: |
                  npm ci
                  npm --prefix ${{ inputs.path }} ci
            - name: Build UI
              run: |
                  npm --prefix ${{ inputs.path }} run build
    format:
        runs-on: ubuntu-latest
        needs: changed
        if: ${{ needs.changed.outputs.ui == 'true' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Run formatters
              run: |
                  npx prettier --check ${{ inputs.path }}
    lint:
        runs-on: ubuntu-latest
        needs: changed
        if: ${{ needs.changed.outputs.ui == 'true' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install Dependencies
              run: |
                  npm ci
                  npm --prefix ${{ inputs.path }} ci
            - name: Run linters
              run: |
                  ./node_modules/.bin/eslint ${{ inputs.path }} --max-warnings 0 --ext .js,.jsx,.ts,.tsx
                  ./node_modules/.bin/npmPkgJsonLint ${{ inputs.path }}
    unit-test:
        runs-on: ubuntu-latest
        needs: changed
        if: ${{ needs.changed.outputs.ui == 'true' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install Dependencies
              run: |
                  npm ci
                  npm --prefix ${{ inputs.path }} ci
            - name: Run Unit Tests
              run: |
                  ./node_modules/.bin/jest --testPathPattern=${{ inputs.path }} --verbose
